Dream.CMMI.Site/Controllers/CmmiProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Dream.CMMI.Site.Controllers
{
    public class CmmiProjectController : ManageControllerBase<CmmiProjectService,CmmiProject>
    {
        //
        // GET: /CmmiProject/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Dream.CMMI.Site/Views/Shared/CE.cshtml
@model Dream.CMMI.CmmiProject

@{
    ViewBag.Title = "CE";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CE</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>CmmiProject</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.ProjectNo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ProjectNo)
            @Html.ValidationMessageFor(model => model.ProjectNo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ProjectName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ProjectName)
            @Html.ValidationMessageFor(model => model.ProjectName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ProjectDiscription)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ProjectDiscription)
            @Html.ValidationMessageFor(model => model.ProjectDiscription)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.StartupTime)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.StartupTime)
            @Html.ValidationMessageFor(model => model.StartupTime)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Sort)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Sort)
            @Html.ValidationMessageFor(model => model.Sort)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CreateTime)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CreateTime)
            @Html.ValidationMessageFor(model => model.CreateTime)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Dream.CMMI.Site/Views/Shared/Create.cshtml
@model Dream.EntityBase
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var propertys = Html.Metadata();
}

<div class="form-horizontal">


    @using (Html.BeginForm())
    {
    <div>
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <div class="form-body">
            @foreach (var property in propertys)
            {

                if (property.IsIdentity) { continue; }
                if (property.CreateMode == Dream.ShowMode.Show)
                {
                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="@property.PropertyName">@Html.DisplayName(property.PropertyName)</label>

                        <div class="col-sm-10">
                            <span>@Html.Editor(property.PropertyName) </span>

                            <span class="help-block">@Html.ValidationMessage(property.PropertyName)</span>
                        </div>
                    </div>
                }
                else if (property.CreateMode == Dream.ShowMode.Hidden)
                {
                    Html.Hidden(property.PropertyName);
                }
                else { }

            }
        </div>
        <div class="form-actions">
            <div class="row">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="保存" class="btn  btn-primary " />
                    <a href="@Request.UrlReferrer" class="btn btn-info">返回列表</a>

                </div>
            </div>
        </div>
    </div>
    }

</div>

Dream.CMMI.Site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <title>@ViewBag.Title - 我的 ASP.NET MVC 应用程序</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap-3.3.5-dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/easyui-1.4.5/themes/default/easyui.css" rel="stylesheet" />
    <link href="~/Content/Style.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    <script src="~/Content/bootstrap-3.3.5-dist/js/bootstrap.js"></script>
    <script src="~/Content/easyui-1.4.5/jquery.easyui.min.js"></script>
    @RenderSection("scripts", required: false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("应用程序名称", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("主页", "Index", "Home")</li>
                    <li>@Html.ActionLink("项目", "Create", "CmmiProject")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 应用程序</p>
        </footer>
    </div>

</body>
</html>